name: Actualizar Lista IPTV

on:
  schedule:
    # Se ejecuta automáticamente cada 3 horas
    - cron: '0 */3 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la web de GitHub
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Código de salida
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: pip install requests

    - name: Ejecutar Extractor
      run: python actualizar.py

    - name: Guardar cambios y subir a GitHub
      run: |
        git config --local user.email "github-actions[bot]@://
        github.com
        "
        git config --local user.name "github-actions[bot]"
        git add lista.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Lista actualizada automáticamente" && git push)
