name: Actualizar Lista IPTV

on:
  schedule:
    # Se ejecuta automáticamente cada 3 horas
    - cron: '0 */3 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la web de Usa el código con precaución.yamlGitHubUsa el código con precaución.yaml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Fuerza a las acciones antiguas a trabajar de forma nativa en Node 24 eliminando el aviso
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Código de salida
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: pip install requests

    - name: Ejecutar Extractor
      run: python actualizar.py

    - name: Guardar cambios y subir a GitHub
      run: |
        git config --local user.email "github-actions[bot]@://Usa el código con precaución.yamlgithub.comUsa el código con precaución.yaml"
        git config --local user.name "github-actions[bot]"
        git add lista.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Lista actualizada automáticamente" && git push)
